#!/bin/bash
#######################
# Constants
flag='0'

#######################
# Config Variables
session_name="rails"
first_window_name="first"
second_window_name="second"
base_pane_command="rapp && rapps"
server_start_comand="rails s"
tests_start_comand="guard"
project_open_command="rappo"
console_open_command="rails c"

#######################
# Addpanes
add_panes() {
  tmux split-window -h -t "${session_name}"
  tmux split-window -v -t "${session_name}"
  tmux send-keys -t "${session_name}":"${first_window_name}".1 "${base_pane_command}" C-m
  tmux send-keys -t "${session_name}":"${first_window_name}".2 "${base_pane_command}" C-m
  tmux send-keys -t "${session_name}":"${first_window_name}".3 "${base_pane_command}" C-m
  tmux send-keys -t "${session_name}":"${first_window_name}".2 "${server_start_comand}"
  tmux send-keys -t "${session_name}":"${first_window_name}".3 "${tests_start_comand}"
}

#######################
# Tmux server start
tmux_session_start() {
  if [ "${flag}" != '1' ] ;then
    echo "Session ${session_name} start..."
    tmux new-session -s ${session_name} -n ${first_window_name} -d
    add_panes
  fi
}

#######################
# Rails server start
rails_server_start() {
  tmux send-keys -t "${session_name}":"${first_window_name}".2 C-m
}

#######################
# Guard start
guard_tests_start() {
  tmux send-keys -t "${session_name}":"${first_window_name}".3 C-m
}

#######################
# Open project in Sublime Text
open_project() {
  tmux send-keys -t "${session_name}":"${first_window_name}".1 "${project_open_command}" C-m
}

#######################
# Ruby console start
ruby_console_start() {
  tmux send-keys -t "${session_name}":"${first_window_name}".1 "${console_open_command}" C-m
}

#######################
# error_param
error_param() {
  tmux kill-session
  echo "Session ${session_name} killed..."
  echo "Parameter is incorrect! Avaliable parameters: 
      -s for start Rails server
      -t for start Gusrd server
      -o for open project in Sublime Text
      -c for open Ruby concole"
  exit 1
}

if [ ! ${1} ] ;then
  tmux_session_start
fi

while [ ${1} ] ;do
  case ${1} in
    -s)
      tmux_session_start
      rails_server_start
      flag='1'
      shift 1
    ;;
    -t)
      tmux_session_start
      guard_tests_start
      flag='1'
      shift 1
    ;;
    -o)
      tmux_session_start
      open_project
      flag='1'
      shift 1
    ;;
    -c)
      tmux_session_start
      ruby_console_start
      flag='1'
      shift 1
    ;;
    *)
      error_param
    ;;
  esac
done

echo "Success!"
tmux select-pane -L -t "${session_name}"
tmux resize-pane -R -t "${session_name}":"${first_window_name}".1 25
tmux new-window  -n "${second_window_name}" -t "${session_name}"
tmux select-window -t "${session_name}":"${first_window_name}"
tmux attach -t "${session_name}"
