#!/bin/bash
#######################
# Constants
flag='0'

#######################
# Config Variables
session_name="rails"
first_window_name="first"

#######################
# Addpanes
add_panes() {
  tmux split-window -h -t "${session_name}"
  tmux split-window -v -t "${session_name}"
  tmux send-keys -t "${session_name}":1.1 'rapp && rapps' C-m
  tmux send-keys -t "${session_name}":1.2 'rapp && rapps' C-m
  tmux send-keys -t "${session_name}":1.3 'rapp && rapps' C-m
  tmux send-keys -t "${session_name}":1.2 'rails s'
  tmux send-keys -t "${session_name}":1.3 'guard'
}

#######################
# Tmux server start
tmux_session_start() {
  if [ "${flag}" != '1' ] ;then
    echo "Session ${session_name} start..."
    tmux new-session -s ${session_name} -n ${first_window_name} -d #имя сессии rails имя окна first создаем сессию и деатачимся
    add_panes
  fi
}

#######################
# Rails server start
rails_server_start() {
  tmux send-keys -t "${session_name}":1.2 C-m
}

#######################
# Guard start
guard_tests_start() {
  tmux send-keys -t "${session_name}":1.3 C-m
}

#######################
# Open project in Sublima Text
open_project() {
  tmux send-keys -t "${session_name}":1.1 'rappo' C-m
}

#######################
# Ruby console start
ruby_console_start() {
  tmux send-keys -t "${session_name}":1.1 'rails c' C-m
}

#######################
# error_param
error_param() {
  tmux kill-session
  echo "Session ${session_name} killed..."
  echo "Parameter is incorrect! Avaliable parameters: 
      -s for start Rails server
      -t for start Gusrd server
      -o for open project in Sublima Text
      -c for open Ruby concole"
  exit 1
}

if [ ! ${1} ] ;then
  tmux_session_start
fi

while [ ${1} ] ;do
  case ${1} in
    -s)
      tmux_session_start
      rails_server_start
      flag='1'
      shift 1
    ;;
    -t)
      tmux_session_start
      guard_tests_start
      flag='1'
      shift 1
    ;;
    -o)
      tmux_session_start
      open_project
      flag='1'
      shift 1
    ;;
    -c)
      tmux_session_start
      ruby_console_start
      flag='1'
      shift 1
    ;;
    *)
      error_param
    ;;
  esac
done

echo "Success!"
tmux select-pane -L -t "${session_name}"
tmux resize-pane -R -t "${session_name}":1.1 25
tmux attach -t "${session_name}"
